### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by kloneets** [efficiently/larasset#10]
Larasset is best asset system I ever used. Now I want to migrate one of my projects from L4.2 to L5, but I cannot install larasset because of dependency conflicts.

Do you plan to work on L5 support?

**Comment by tortuetorche** [comment]
Of course but my priority is to update [Autority-Controller](https://github.com/efficiently/authority-controller) package first, because it's more popular.

**Comment by tortuetorche** [comment]
And the Codeception package need to support Laravel 5, then I could run my tests with L5.
See: https://github.com/Codeception/Codeception/pull/1704

**Comment by tortuetorche** [comment]
Larasset is now compatible with **Laravel 5.0**, hurray!
You can install it with the [1.0 branch](https://github.com/efficiently/larasset/tree/1.0) and here a sample of `composer.json` to install it in your Laravel 5 application:

```json
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"laravel/framework": "5.0.*",
		"efficiently/larasset": "1.0.*"
	},
	"require-dev": {
		"phpunit/phpunit": "~4.0",
		"phpspec/phpspec": "~2.1"
	},
	"autoload": {
		"classmap": [
			"database"
		],
		"psr-4": {
			"App\\": "app/"
		}
	},
	"autoload-dev": {
		"classmap": [
			"tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php -r \"copy('.env.example', '.env');\"",
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	},
	"prefer-stable": true,
	"minimum-stability": "dev"
}

```

**Comment by tortuetorche** [comment]
Then you can update the `larasset-js` module:
```bash
npm update -g larasset-js
```
