### ISSUE TITLE
Trouble installing Larasset on Laravel 5 installation

### ISSUE THREAD

**Issue by RodrigoBalest** [efficiently/larasset#11]
Hi.
After issuing `composer require efficiently/larasset:1.0.x-dev`, I got the following error:

```
  Problem 1
    - Installation request for efficiently/larasset 1.0.x-dev -> satisfiable by
efficiently/larasset[1.0.x-dev].
    - efficiently/larasset 1.0.x-dev requires efficiently/jquery-laravel ~2.0.0
-> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common
 problems.
```
Maybe it shouldn't require `efficiently/jquery-laravel: 2.0.x-dev`? I didn't find any tag above 1.0.7 on jquery-laravel repo. And, taking a look at the composer.json at the `master` branch, it seems it wouldn't work with laravel 5.

Thanks!

**Comment by tortuetorche** [comment]
Hi @RodrigoBalest,

You can read this comment to configure your `composer.json`:
https://github.com/efficiently/larasset/issues/10#issuecomment-77817020

Cheers,
Tortue Torche

**Comment by RodrigoBalest** [comment]
Hi Tortue Torche!

I think I missed the `prefer-stable` part.
This is what happens when you're working tired late at night! :blush: 
I will try it out.

Thanks!
