### ISSUE TITLE
Question: How to use Larasset with modules?

### ISSUE THREAD

**Issue by RodrigoBalest** [efficiently/larasset#12]
I'm using Larasset and I like it a lot. But now I'm trying to separate my app into packages or modules, one responsible for each feature (user management, file uploads, blog posts, and so on).

So my question is how can Larasset be used in a 'modularized' app like this, where each module/package may add its own assets?

Should I publish those assets and add them to application.(css|js) file everytime a new package/module is activated/updated?
 
Thanks!

**Comment by tortuetorche** [comment]
Hi Rodrigo,

Good question, here some docs about:
* [Manifest fiels and directives](https://github.com/efficiently/larasset/wiki/Asset-pipeline#manifest-files-and-directives)
* [Mincer directives](https://github.com/nodeca/mincer/#mincer-directives)

For automatically adding assets from packages in your application, you can read this [Wiki section](https://github.com/efficiently/larasset/wiki/Asset-pipeline#adding-assets-to-your-packages).
Here an sample with my jQuery-Laravel package: https://github.com/efficiently/jquery-laravel/blob/2.0/src/Efficiently/JqueryLaravel/JqueryLaravelServiceProvider.php#L25

You can also manually adding assets of existing packages in your application if you config their paths in the `config/larasset.php` file. Look at the source code of my [Larasset demo](https://github.com/efficiently/laravel_larasset_app/blob/bootstrap-l5/config/larasset.php#L64) to have a real world sample.

Cheers,
Tortue Torche
