### ISSUE TITLE
npm install problem on Yosemite.

### ISSUE THREAD

**Issue by tmunzar-jfish** [efficiently/larasset#13]
If I'm correct, one of the dependencies of the larasset-js npm package is node-sass@1.2.3.

However node-sass@1.2.3 fails to install on my Yosemite OSX (10.10.2). The latest version of node-sass (i.e. 2.1.1) however installs without any issues.

Is there are a way for me to install larasset-js without it having to depend on an older version of node-sass?

**Comment by tortuetorche** [comment]
Hi @tmunzar-jfish,

Do you plan to use SASS or SCSS in your application ?

Cheers,
Tortue Torche

**Comment by tmunzar-jfish** [comment]
@tortuetorche I figured it out. node-sass@1.2.3 wasn't installing because of the my node.js being at an incompatible version (0.12.*). I downgraded node to a 0.10.* and it solved the issue for me.

The application is using SCSS.

**Comment by tortuetorche** [comment]
Glad to see your issue is resolved.
I'll see if I bump the node-sass version in the next `larasset-js` release.

**Comment by tmunzar-jfish** [comment]
@tortuetorche I think you should have it be able to use a new version of node-sass. Seems like larasset is having problems compiling Zurb Foundation 5 scss files properly.
