### ISSUE TITLE
Can't composer update

### ISSUE THREAD

**Issue by FiloSpaTeam** [efficiently/larasset#16]
![err1](https://cloud.githubusercontent.com/assets/2974561/8481479/99b3857e-20e3-11e5-8011-6c968686f88a.png)
Later #15 solved.

**Comment by tortuetorche** [comment]
If you have a Laravel 4.1 use the Larasset 0.9 branch instead of the master branch:
```js
"efficiently/larasset": "0.9.*",
```

**Comment by FiloSpaTeam** [comment]
yeah, solver now :+1: sorry!
