### ISSUE TITLE
How do I run the assets server in production?(not a bug)

### ISSUE THREAD

**Issue by cmosh** [efficiently/larasset#19]
(not a bug)
It may seem obvious to most but I have placed all my assets in the pipline and run
' php artisan larasset:precompile --assets-env production '
In order to serve these assets I then used the php artisan larasset:serve command because I saw no other way, now if I close the cmd ny assets are not served.
{ I am new to asset pipelines }

**Comment by tortuetorche** [comment]
Hi @cmosh,

> In production, Larasset precompiles these files to public/assets by default. The precompiled copies are then served as static assets by the web server. The files in app/assets are never served directly in production.
> _From the [The Asset Pipeline Guide](https://github.com/efficiently/larasset/wiki/Asset-pipeline#how-to-use-the-asset-pipeline)_

So the precompiled files generated by Larasset are placed in the `public\assets` directory of your Laravel application.
Then your Web server <small>(Apache HTTP, NGINX...)</small> must serve them as static files.
I'm sure you can find in your favorite search engine how to accomplish this :wink:

For advance configuration between your static files and your Web server, you can also read [this section](https://github.com/efficiently/larasset/wiki/Asset-pipeline#far-future-expires-header) of the Asset Pipeline guide.

Cheers,
Tortue Torche

**Comment by cmosh** [comment]
Thanks again.
