### ISSUE TITLE
Almost works with laravel 5.2

### ISSUE THREAD

**Issue by cmosh** [efficiently/larasset#20]
Just need to Alias it as laravel 5.1 because of version constraints in jquery laravel

**Comment by tortuetorche** [comment]
Hi Clive,

Thank you for this report!

I've updated some dependencies, can you try to reinstall Larasset with your Laravel 5.2 application?
For now, you should use the `dev-master` version of Larasset, then I'll create a `1.2` branch for both Laravel 5.1 and 5.2 compatibilities.

Cheers,
Tortue Torche

**Comment by cmosh** [comment]
I've reinstalled and used it for about a week and it works just as well. 
Thanks for the quick response

**Comment by tortuetorche** [comment]
Larasset now supports officially Laravel 5.2 !
Here the dedicated branch: https://github.com/efficiently/larasset/tree/1.2
