### ISSUE TITLE
less compile not working with less methods

### ISSUE THREAD

**Issue by fifastar** [efficiently/larasset#21]
Hi Team,

Larasset's been working perfectly on my project(on my mac system locally and centos production environment). Recently one of my friend started to use it on his homestead with Ubantu system, after everything is set up, normal less code can be compiled as usual, however, it turns out once less file contains less method/function, the compile failed and there is no compiled css file with 500 internal error. I tried to put same less code on my local mac system, it's working perfectly. Can anyone tell me why ? Thanks in advance!

Regards,
Allen.

**Comment by kloneets** [comment]
Without real errors we can not help you, but it is more likely [less](https://github.com/less/less.js) problem not larasset's.

**Comment by tortuetorche** [comment]
Hi @fifastar,

It'll be really useful that your friend send his `storage/logs/larasset_server.log` (or `app/storage/logs/larasset_server.log`) file here.

Cheers,
Tortue Torche

**Comment by fifastar** [comment]
Really appreciate your replies @kloneets and @tortuetorche. I checked both on my mac and my friend's working env, there is no larasset_server.log file under storage/logs folder. All logs under that folder are Laravel logs. Any idea? Thank you.

**Comment by tortuetorche** [comment]
Did your friend follows the installation instructions of Larasset? Without a complete error logs it's difficult to help you...

**Comment by fifastar** [comment]
@tortuetorche Yes, we all did followed the installation listed on github. As I said, I've been using it for my production project for almost a year and it's working perfectly. I really like to provide error logs for your deeper diagnostics but my question was, I couldn't see larasset_server.log based on your instruction....

**Comment by tortuetorche** [comment]
When on his local machine, he launch this command
```bash
php artisan server
```
Then go to the main page of  your application with your Web browser, basically http://localhost:8000
Is there any `larasset_server.log` created?
And last but not least, can he test this command: `which larasset` and send the output here.

**Comment by fifastar** [comment]
We used other web servers with command php artisan larasset:serve --host=xxx.xxx.xxx.xxx in our projects. Anyway, will let him do exactly as what you listed and let you know the result later. Thank you again.

**Comment by tortuetorche** [comment]
OK, this is why `larasset_server.log` isn't created, but instead the error logs should be shown in the console.

**Comment by kloneets** [comment]
Did you check file and folder permissions? It is another thing that could go wrong on Linux box :)

**Comment by fifastar** [comment]
@tortuetorche yes, I can see error log shown in console with larasset:serve command. Please take a look at the error log below and see if it helps. 

![8b4569127d4bd8818f0f6be6627d5c1a](https://cloud.githubusercontent.com/assets/3735046/18080139/b73e815c-6ec6-11e6-8898-5dd7eb6b6574.jpg)

**Comment by fifastar** [comment]
@kloneets yes, folder permission could be the reason, but like what I mentioned in my original thread, the strangest thing is that, if we only put normal css style, like 'fontsize: 16px' on less files, css can be compiled and everything works fine. However, once less file contains a method/function, it just failed the css compiling somehow.

**Comment by tortuetorche** [comment]
Thank you, so can you send the test.less file?
Maybe related to https://github.com/madskristensen/WebEssentials2013/issues/1696

If `test.less` is empty, try to add this line inside:
```less
/**/
```

**Comment by fifastar** [comment]
@tortuetorche Yes! Adding /**/ completely fixed this problem. And I believe that's why once it only contains method/function, if it's not used yet, empty result failed the whole css compiling, just exactly as what adskristensen/WebEssentials2013#1696 refers to. The only strange thing for now is,  we were confused by same empty result worked fine on my mac, but it did not on my friends' working env. Anyway, thank you for all your time and advice, this helps a a lot! @kloneets @tortuetorche

**Comment by tortuetorche** [comment]
You should check that all your files are encoding in UTF-8 without BOM and with UNIX (LF) line endings.

**Comment by fifastar** [comment]
Yes, just checking with my friend and I believe that's the root cause based on 'LESS: Unexpected token u' thread.

**Comment by fifastar** [comment]
Confirmed with my friends that all less file we used are all in UTF-8 format. Anyway, really appreciate your help and advices, thank you @tortuetorche and @kloneets .

**Comment by tortuetorche** [comment]
Hi @fifastar,

I'm closing this issue.
Feel free to reopen it, if you have any problems.

Cheers,
Tortue Torche

**Comment by fifastar** [comment]
@tortuetorche No problem. Everything works perfectly now. Thank you!

Cheers,
Allen.
