### ISSUE TITLE
CSS minification issues

### ISSUE THREAD

**Issue by tsiedsma** [efficiently/larasset#7]
I'm seeing some issues when compiling assets for production.  The CSS minification is stripping some items.

*property: value; is stripped of the asterisk.  This needs to be fixed.
http://www.javascriptkit.com/dhtmltutors/csshacks3.shtml

It's also stripping out the Browser Extension properties completely.  The minified CSS does not contain any Browser Extension properties...
-webkit-border-radius: 0;
-moz-border-radius: 0;

**Comment by lhdev** [comment]
This issue has come up again.  Has something changed?

**Comment by tortuetorche** [comment]
No, I test it again and it's OK for me.

**Comment by lhdev** [comment]
I'm having the EXACT same issue though. Do I need to modify the mincer config again?


On Mar 5, 2015, at 3:22 AM, Tortue Torche <notifications@github.com<mailto:notifications@github.com>> wrote:


No, I test it again and it's OK for me.

-

**Comment by tortuetorche** [comment]
Maybe you can clear your NPM cache and check if you don't have multiple `larasset` executable files.

**Comment by tortuetorche** [comment]
The `mincer` config is fixed if you install `larasset` >=0.9.7

**Comment by lhdev** [comment]
larasset-js@0.9.8<mailto:larasset-js@0.9.8> is installed globally, it does not exist in the local node_modules directory.  Any other ideas?  The CSS is broken when minified, not when it’s just combined and un-minified.

**Comment by tortuetorche** [comment]
Can you test with just a little CSS file like in your [sample](https://github.com/efficiently/larasset/issues/7#issuecomment-65243652)?

**Comment by tortuetorche** [comment]
Any news?

**Comment by lhdev** [comment]
No, I have not had a chance to try a sample CSS file.  I just know my CSS was broken, you introduced a fix and it worked.  Now it is broken again and my CSS hasn’t changed…

**Comment by lhdev** [comment]
I know its been 5 months, but this same issue is still happening.  I've reinstalled larasset-js and cleared the npm cache.  Recompiling via production removes the hacks from the CSS.

the example above is still valid, that's exactly what is happening in my minified css file.
