### ISSUE TITLE
Disabling Source Maps and precompile issues

### ISSUE THREAD

**Issue by lhdev** [efficiently/larasset#8]
Hello,
I hate to open an issue for this, but your documentation is incomplete regarding disabling source maps.
How do you disable source maps for production?

Also, the following command results in the deprecation warning
``php artisan larasset:precompile --environment production``

However, this command results in the following error.
``php artisan larasset:precompile --assets-env production``

Error:
[InvalidArgumentException]
There are no commands defined in the "larasset" namespace.

**Comment by lhdev** [comment]
Hello, any update on adding the option to disable sourcemaps?

**Comment by tortuetorche** [comment]
@lhdev Feel free to reopen this issue if you have any problems.

**Comment by lhdev** [comment]
Still having the issue.
Updated both composer and npm, confirmed the new versions are installed.
Updated app/config/packages/efficiently/larrasset/config.php, added 'sourceMaps' => false to the array.

Updated my env with 'ASSETS_ENV'               => 'production' and then recompiled assets.  The maps are still generated and linked at the bottom of .css and .js files.

**Comment by tortuetorche** [comment]
Can you try again in few minutes, please ?

**Comment by tortuetorche** [comment]
It's OK now, sorry I forgot to publish the `larasset-js` module on npm.

```bash
npm update -g larasset-js
```

**Comment by lhdev** [comment]
Works as expected, thank you for implementing this feature!

**Comment by tortuetorche** [comment]
You're welcome, the next step is Laravel 5 support
